CREATE EXTERNAL TABLE IF NOT EXISTS [your database].iperf (
  bandwidth_direction CHAR(4),
  bandwidth_max FLOAT,
  bandwidth_mean FLOAT,
  bandwidth_median FLOAT,
  bandwidth_min FLOAT,
  bandwidth_p10 FLOAT,
  bandwidth_p25 FLOAT,
  bandwidth_p75 FLOAT,
  bandwidth_p90 FLOAT,
  bandwidth_stdev FLOAT,
  benchmark_version CHAR(8),
  collectd_rrd VARCHAR(255),
  cpu_client FLOAT,
  cpu_server FLOAT,
  iperf_bandwidth CHAR(8),
  iperf_cmd VARCHAR(255),
  iperf_concurrency TINYINT,
  iperf_interval TINYINT,
  iperf_len INT,
  iperf_mss INT,
  iperf_nodelay TINYINT,
  iperf_num INT,
  iperf_parallel TINYINT,
  iperf_reverse TINYINT,
  iperf_server VARCHAR(64),
  iperf_server_instance_id VARCHAR(96),
  iperf_server_os CHAR(32),
  iperf_server_provider CHAR(32),
  iperf_server_provider_id CHAR(24),
  iperf_server_region CHAR(32),
  iperf_server_service CHAR(32),
  iperf_server_service_id CHAR(24),
  iperf_time SMALLINT,
  iperf_tos CHAR(8),
  iperf_udp TINYINT,
  iperf_version CHAR(8),
  iperf_warmup SMALLINT,
  iperf_window INT,
  iperf_zerocopy TINYINT,
  iteration TINYINT,
  jitter_max FLOAT,
  jitter_mean FLOAT,
  jitter_median FLOAT,
  jitter_min FLOAT,
  jitter_p10 FLOAT,
  jitter_p25 FLOAT,
  jitter_p75 FLOAT,
  jitter_p90 FLOAT,
  jitter_stdev FLOAT,
  loss_max FLOAT,
  loss_mean FLOAT,
  loss_median FLOAT,
  loss_min FLOAT,
  loss_p10 FLOAT,
  loss_p25 FLOAT,
  loss_p75 FLOAT,
  loss_p90 FLOAT,
  loss_stdev FLOAT,
  meta_compute_service CHAR(32),
  meta_compute_service_id CHAR(24),
  meta_cpu CHAR(32),
  meta_cpu_cache CHAR(32),
  meta_cpu_cores TINYINT,
  meta_cpu_speed FLOAT,
  meta_hostname CHAR(64),
  meta_instance_id CHAR(96),
  meta_memory CHAR(32),
  meta_memory_gb SMALLINT,
  meta_memory_mb INT,
  meta_os CHAR(32),
  meta_provider CHAR(32),
  meta_provider_id CHAR(24),
  meta_region CHAR(32),
  meta_resource_id CHAR(32),
  meta_run_group_id CHAR(32),
  meta_run_id CHAR(32),
  meta_test_id CHAR(64),
  report_pdf VARCHAR(255),
  report_zip VARCHAR(255),
  same_instance_id TINYINT,
  same_os TINYINT,
  same_provider TINYINT,
  same_region TINYINT,
  same_service TINYINT,
  test_started TIMESTAMP,
  test_stopped TIMESTAMP,
  transfer INT
)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
  ESCAPED BY '\\'
  LINES TERMINATED BY '\n'
LOCATION 's3://[your S3 bucket]/path/to/csv/files/'
TBLPROPERTIES (
  'skip.header.line.count'='1'
);